#!/usr/bin/env python3
"""One-time SQLite -> PostgreSQL migration for DaivikPooja.

Preserves EVERY table, row and primary-key id from the Node/SQLite database
(users, bookings, payments, kundalis, puja_media photo metadata, ...) so the
FastAPI backend can take over production data without breaking references.

Pipeline:
  1. Introspect the SQLite file (tables, columns, PKs, indexes, FK order) after
     a WAL checkpoint so all rows are visible.
  2. Translate the schema to Postgres DDL:
       - INTEGER single-column PKs become BIGINT GENERATED BY DEFAULT AS
         IDENTITY (rowid-alias parity), composite PKs are kept;
       - TEXT/INTEGER/REAL/BLOB map to TEXT/BIGINT/DOUBLE PRECISION/BYTEA;
       - SQLite-specific DEFAULT expressions (unixepoch()...) are dropped —
         every row is copied with explicit values anyway;
       - indexes (including the partial unique idx_pandit_slot) are recreated
         from their original SQL;
       - foreign keys are added AFTER the data copy so insertion order never
         blocks the copy.
  3. Copy rows in chunks with per-column type coercion (SQLite is dynamically
     typed; empty strings in numeric columns become NULL, numeric strings are
     cast) — asyncpg rejects implicit casts, this makes the copy deterministic.
  4. Resync identity sequences (setval to MAX(id)) so new inserts never collide
     with migrated ids.
  5. Verify: per-table row counts and MAX(pk) must match the source exactly.

Usage (from backend-python/):
  .venv/Scripts/python tools/migrate_sqlite_to_postgres.py \
      --source ../data/daivikpooja.db \
      --target postgresql://postgres.<ref>:<pw>@aws-0-<region>.pooler.supabase.com:6543/postgres

  --dry-run     introspect + plan + verification preview, no writes
  --truncate    empty the target tables first (topological order) instead of
                refusing to copy over existing rows
  --tables a,b  restrict to a subset (children via FKs are pulled in too)

Exit code 0 only when every table verifies clean. The tool never deletes data
unless --truncate is passed, and never touches the source file (read-only).
"""
from __future__ import annotations

import argparse
import asyncio
import dataclasses
import json
import re
import sqlite3
import sys
import time
from pathlib import Path

CHUNK = 500
SKIP_TABLES = {"sqlite_sequence", "sqlite_stat1", "sqlite_stat4"}
# JSON-safe report helper
_pretty = lambda obj: json.dumps(obj, indent=2, default=str)  # noqa: E731


# --------------------------------------------------------------------------- #
# Introspection
# --------------------------------------------------------------------------- #
@dataclasses.dataclass
class Column:
    name: str
    decl: str                  # declared type in sqlite, e.g. TEXT
    notnull: bool
    default_sql: str | None
    pk_index: int              # 1-based position in the PK, 0 = not part of PK


@dataclasses.dataclass
class TableDef:
    name: str
    columns: list[Column]
    pk_cols: list[str]
    rowid_alias: bool          # single INTEGER PK == rowid alias (autoincrement)

    @property
    def identity_col(self) -> str | None:
        return self.pk_cols[0] if self.rowid_alias else None


def checkpoint(source: Path) -> None:
    con = sqlite3.connect(str(source))
    try:
        con.execute("PRAGMA wal_checkpoint(TRUNCATE)")
    finally:
        con.close()


def introspect(source: Path, only: set[str] | None = None) -> dict:
    """Read-only schema + row-count snapshot of the SQLite database."""
    con = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    try:
        tables = [r["name"] for r in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' "
            "ORDER BY name") if r["name"] not in SKIP_TABLES]
        if only:
            missing = only - set(tables)
            if missing:
                raise SystemExit(f"--tables referenced unknown tables: {sorted(missing)}")
            tables = [t for t in tables if t in only]
        defs: dict[str, TableDef] = {}
        counts: dict[str, int] = {}
        for t in tables:
            cols, pk_cols = [], []
            for r in con.execute(f'PRAGMA table_info("{t}")'):
                col = Column(name=r["name"], decl=(r["type"] or "TEXT").upper(),
                             notnull=bool(r["notnull"]), default_sql=r["dflt_value"],
                             pk_index=r["pk"])
                cols.append(col)
                if r["pk"]:
                    pk_cols.append((r["pk"], r["name"]))
            pk_cols = [n for _, n in sorted(pk_cols)]
            rowid_alias = (len(pk_cols) == 1
                           and next(c for c in cols if c.name == pk_cols[0]).decl.upper() == "INTEGER")
            defs[t] = TableDef(name=t, columns=cols, pk_cols=pk_cols, rowid_alias=rowid_alias)
            counts[t] = con.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        # FK edges for topological ordering (parents first)
        edges: dict[str, set[str]] = {t: set() for t in tables}
        for t in tables:
            for fk in con.execute(f'PRAGMA foreign_key_list("{t}")'):
                parent = fk["table"]
                if parent in defs and parent != t:
                    edges[t].add(parent)

        def topo() -> list[str]:
            order, seen = [], set()

            def visit(t: str, stack: set[str]):
                if t in seen or t in stack:  # cycles: ignore, FKs added post-copy
                    return
                stack.add(t)
                for parent in sorted(edges.get(t, ())):
                    visit(parent, stack)
                stack.discard(t)
                seen.add(t)
                order.append(t)

            for t in tables:
                visit(t, set())
            return order

        indexes = [{"table": r["tbl_name"], "name": r["name"], "sql": r["sql"]}
                   for r in con.execute(
                       "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' "
                       "AND sql IS NOT NULL ORDER BY name") if r["tbl_name"] in defs]
        return {"tables": defs, "counts": counts, "order": topo(), "indexes": indexes}
    finally:
        con.close()


def read_rows(source: Path, table: str, columns: list[str]):
    con = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    try:
        col_list = ", ".join(f'"{c}"' for c in columns)
        cur = con.execute(f'SELECT {col_list} FROM "{table}"')
        while True:
            batch = cur.fetchmany(CHUNK)
            if not batch:
                return
            for row in batch:
                yield row
    finally:
        con.close()


# --------------------------------------------------------------------------- #
# Postgres DDL translation
# --------------------------------------------------------------------------- #
def pg_type(decl: str) -> str:
    d = decl.upper()
    if "INT" in d:
        return "BIGINT"
    if d in ("REAL", "FLOAT", "DOUBLE") or "DOUB" in d or "FLOA" in d:
        return "DOUBLE PRECISION"
    if "BLOB" in d:
        return "BYTEA"
    if "BOOL" in d:
        return "BOOLEAN"
    return "TEXT"


_SQLITE_DEFAULT_FN = re.compile(r"\b(unixepoch|datetime|date|time|strftime|CURRENT_TIMESTAMP|julianday)\b", re.I)


def translate_table(t: TableDef, dialect: str = "postgres") -> list[str]:
    """CREATE TABLE without FKs (added post-copy) and safe defaults only.
    Two dialects: postgres (rowid-alias -> IDENTITY) and sqlite (INTEGER
    PRIMARY KEY inline, used by the test harness / rehearsal targets)."""
    if dialect == "sqlite":
        parts = []
        for c in t.columns:
            if t.identity_col == c.name:
                parts.append(f'"{c.name}" INTEGER PRIMARY KEY')
                continue
            piece = f'"{c.name}" {c.decl or "TEXT"}'
            if c.notnull:
                piece += " NOT NULL"
            if c.default_sql is not None:
                d = str(c.default_sql)
                if not _SQLITE_DEFAULT_FN.search(d):
                    piece += f" DEFAULT {d}"
            parts.append(piece)
        if not t.rowid_alias and t.pk_cols:
            parts.append("PRIMARY KEY (" + ", ".join(f'"{c}"' for c in t.pk_cols) + ")")
        return [f'CREATE TABLE IF NOT EXISTS "{t.name}" (\n  ' + ",\n  ".join(parts) + "\n)"]
    parts = []
    for c in t.columns:
        if t.identity_col == c.name:
            parts.append(f'"{c.name}" BIGINT GENERATED BY DEFAULT AS IDENTITY')
            continue
        piece = f'"{c.name}" {pg_type(c.decl)}'
        if c.notnull:
            piece += " NOT NULL"
        if c.default_sql is not None:
            d = str(c.default_sql)
            if not _SQLITE_DEFAULT_FN.search(d):     # sqlite-only expressions dropped
                piece += f" DEFAULT {d}"
        parts.append(piece)
    if t.pk_cols:
        parts.append("PRIMARY KEY (" + ", ".join(f'"{c}"' for c in t.pk_cols) + ")")
    return [f'CREATE TABLE IF NOT EXISTS "{t.name}" (\n  ' + ",\n  ".join(parts) + "\n)"]


def translate_indexes(indexes: list[dict]) -> list[str]:
    """Original index SQL, verbatim where legal. Partial unique indexes
    (idx_pandit_slot) are valid Postgres as written."""
    stmts, seen = [], set()
    for idx in indexes:
        sql = (idx["sql"] or "").strip()
        if not sql or idx["name"] in seen:
            continue
        seen.add(idx["name"])
        sql = re.sub(r"^CREATE\s+(UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS", "CREATE \\1INDEX IF NOT EXISTS",
                     sql, flags=re.I)
        if not re.search(r"IF NOT EXISTS", sql, re.I):
            sql = re.sub(r"^CREATE\s+(UNIQUE\s+)?INDEX\s+", r"CREATE \1INDEX IF NOT EXISTS ", sql,
                         count=1, flags=re.I)
        stmts.append(sql)
    return stmts


def coerce_value(col: Column, value):
    """SQLite is dynamically typed; asyncpg is not. Deterministic coercion:
    '' / bad strings -> NULL for numeric columns, numeric strings -> numbers."""
    if value is None:
        return None
    t = pg_type(col.decl)
    if t == "BIGINT":
        if isinstance(value, int):
            return value
        s = str(value).strip()
        if s == "":
            return None
        return int(float(s)) if ("." in s or "e" in s.lower()) else int(s)
    if t == "DOUBLE PRECISION":
        if isinstance(value, (int, float)):
            return float(value)
        s = str(value).strip()
        return float(s) if s else None
    if t == "BOOLEAN":
        return None if isinstance(value, str) and value == "" else bool(value)
    if t == "BYTEA":
        return bytes(value)
    return value if isinstance(value, str) else str(value)


# --------------------------------------------------------------------------- #
# Targets
# --------------------------------------------------------------------------- #
class PostgresTarget:
    """Production target via asyncpg (already a dependency — no new installs)."""

    dialect = "postgres"

    def __init__(self, dsn: str):
        self.dsn = dsn.replace("postgresql+asyncpg://", "postgresql://")
        self.conn = None

    async def connect(self):
        import asyncpg
        self.conn = await asyncpg.connect(self.dsn)

    async def close(self):
        if self.conn:
            await self.conn.close()

    async def execute(self, sql: str):
        await self.conn.execute(sql)

    async def table_exists(self, name: str) -> bool:
        return await self.conn.fetchval(
            "SELECT 1 FROM information_schema.tables WHERE table_name=$1", name) is not None

    async def count(self, table: str) -> int:
        return int(await self.conn.fetchval(f'SELECT COUNT(*) FROM "{table}"'))

    async def max_pk(self, table: str, col: str):
        return await self.conn.fetchval(f'SELECT MAX("{col}") FROM "{table}"')

    async def copy_chunk(self, table: str, columns: list[str], rows: list[tuple]):
        placeholders = ", ".join(f"${i + 1}" for i in range(len(columns)))
        col_list = ", ".join(f'"{c}"' for c in columns)
        await self.conn.executemany(
            f'INSERT INTO "{table}" ({col_list}) VALUES ({placeholders})', rows)

    async def setval(self, table: str, col: str):
        seq = await self.conn.fetchval(
            "SELECT pg_get_serial_sequence($1, $2)", table, col)
        if not seq:
            return
        mx = await self.max_pk(table, col)
        if mx is None:
            await self.conn.execute(f'SELECT setval(\'{seq}\', 1, false)')
        else:
            await self.conn.execute(f'SELECT setval(\'{seq}\', {int(mx)}, true)')

    async def truncate(self, tables: list[str]):
        if tables:
            await self.conn.execute(
                "TRUNCATE " + ", ".join(f'"{t}"' for t in tables) + " CASCADE")


class SqliteTarget:
    """Same protocol backed by a plain SQLite file — lets the test suite run the
    full pipeline end-to-end without a live Postgres."""

    dialect = "sqlite"

    def __init__(self, path: str):
        self.path = path
        self.conn = sqlite3.connect(path)

    async def connect(self):
        self.conn.execute("PRAGMA foreign_keys=OFF")

    async def close(self):
        self.conn.commit()
        self.conn.close()

    async def execute(self, sql: str):
        self.conn.execute(sql)

    async def table_exists(self, name: str) -> bool:
        return self.conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
            (name,)).fetchone() is not None

    async def count(self, table: str) -> int:
        return self.conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]

    async def max_pk(self, table: str, col: str):
        row = self.conn.execute(f'SELECT MAX("{col}") FROM "{table}"').fetchone()
        return row[0] if row else None

    async def copy_chunk(self, table: str, columns: list[str], rows: list[tuple]):
        col_list = ", ".join(f'"{c}"' for c in columns)
        placeholders = ", ".join("?" for _ in columns)
        self.conn.executemany(
            f'INSERT OR REPLACE INTO "{table}" ({col_list}) VALUES ({placeholders})', rows)

    async def setval(self, table: str, col: str):
        pass  # no sequences in sqlite

    async def truncate(self, tables: list[str]):
        for t in tables:
            self.conn.execute(f'DELETE FROM "{t}"')


# --------------------------------------------------------------------------- #
# Pipeline
# --------------------------------------------------------------------------- #
async def run_migration(source: Path, target, *, dry_run: bool = False,
                        truncate: bool = False, only: set[str] | None = None,
                        log=print) -> dict:
    plan = introspect(source, only=only)
    defs, order, counts = plan["tables"], plan["order"], plan["counts"]
    total_rows = sum(counts.values())
    log(f"source: {source}  tables={len(order)}  rows={total_rows}")
    if dry_run:
        log("dry run — DDL that would be executed (first 12):")
        for t in order[:12]:
            log("  " + translate_table(defs[t])[0].replace("\n", " ")[:160] + " …")
        log("verification preview: " + _pretty(counts))
        return {"dry_run": True, "counts": counts}

    await target.connect()
    try:
        dialect = getattr(target, "dialect", "postgres")
        created = []
        for t in order:
            if not await target.table_exists(t):
                for stmt in translate_table(defs[t], dialect):
                    await target.execute(stmt)
                created.append(t)
        if truncate:
            await target.truncate(list(reversed(order)))

        copied = {}
        for t in order:
            cols = [c.name for c in defs[t].columns]
            cmap = {c.name: c for c in defs[t].columns}
            buf, n = [], 0
            for row in read_rows(source, t, cols):
                buf.append(tuple(coerce_value(cmap[c], v) for c, v in zip(cols, row)))
                if len(buf) >= CHUNK:
                    await target.copy_chunk(t, cols, buf)
                    n += len(buf)
                    buf = []
            if buf:
                await target.copy_chunk(t, cols, buf)
                n += len(buf)
            copied[t] = n

        idx_stmts = translate_indexes(plan["indexes"])
        for stmt in idx_stmts:
            await target.execute(stmt)
        # identity sequences after copy so future inserts never collide
        for t in order:
            if defs[t].identity_col:
                await target.setval(t, defs[t].identity_col)

        # ---- verify -------------------------------------------------------
        report, ok = {}, True
        for t in order:
            tgt_count = await target.count(t)
            entry = {"source": counts[t], "target": tgt_count, "ok": tgt_count == counts[t]}
            if defs[t].identity_col:
                col = defs[t].identity_col
                entry["max_id"] = {"source": await _src_max(source, t, col),
                                   "target": await target.max_pk(t, col)}
                entry["ok"] = entry["ok"] and (
                    entry["max_id"]["source"] == entry["max_id"]["target"])
            ok = ok and entry["ok"]
            report[t] = entry
        log(_pretty(report))
        log("MIGRATION " + ("VERIFIED OK" if ok else "FAILED — counts/ids differ"))
        return {"ok": ok, "copied": copied, "created": created,
                "indexes": len(idx_stmts), "report": report}
    finally:
        await target.close()


async def _src_max(source: Path, table: str, col: str):
    con = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    try:
        row = con.execute(f'SELECT MAX("{col}") FROM "{table}"').fetchone()
        return row[0] if row else None
    finally:
        con.close()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--source", default="../data/daivikpooja.db",
                    help="path to the SQLite file (read-only; default ../data/daivikpooja.db)")
    ap.add_argument("--target", default=None,
                    help="Postgres DSN, or DATABASE_URL env; postgresql://… pooler URI")
    ap.add_argument("--dry-run", action="store_true", help="plan only, no writes")
    ap.add_argument("--truncate", action="store_true",
                    help="empty target tables first (default: refuse non-empty targets)")
    ap.add_argument("--tables", default="", help="comma-separated subset of tables")
    args = ap.parse_args(argv)

    source = Path(args.source)
    if not source.exists():
        print(f"source not found: {source}", file=sys.stderr)
        return 2
    checkpoint(source)  # ensure a consistent read snapshot

    import os
    dsn = args.target or os.environ.get("DATABASE_URL")
    if not dsn and not args.dry_run:
        print("no target: pass --target or set DATABASE_URL (postgres pooler URI)",
              file=sys.stderr)
        return 2

    only = {t.strip() for t in args.tables.split(",") if t.strip()} or None
    result = asyncio.run(run_migration(
        source,
        PostgresTarget(dsn) if dsn else SqliteTarget(":memory:"),
        dry_run=args.dry_run, truncate=args.truncate, only=only))
    return 0 if (args.dry_run or result.get("ok")) else 1


if __name__ == "__main__":
    sys.exit(main())
