"""Tests for tools/migrate_sqlite_to_postgres.py.

The end-to-end tests run the FULL pipeline against a synthetic source and —
when present — against the repo's real production SQLite file
(../data/daivikpooja.db), copying into a throwaway target and verifying every
table count and max(id). That is the exact dress rehearsal the production
cutover will run, minus the Postgres DSN."""
import importlib.util
import sqlite3
import sys
from pathlib import Path

import pytest

TOOL = Path(__file__).resolve().parents[1] / "tools" / "migrate_sqlite_to_postgres.py"
spec = importlib.util.spec_from_file_location("migrate_tool", TOOL)
mig = importlib.util.module_from_spec(spec)
sys.modules["migrate_tool"] = mig   # dataclass introspection needs the module registered
spec.loader.exec_module(mig)

REPO = Path(__file__).resolve().parents[2]
REAL_DB = REPO / "data" / "daivikpooja.db"


def _make_source(tmp_path: Path) -> Path:
    """Synthetic Node-style database: TEXT ids, INTEGER rowid-alias tables,
    JSON-in-TEXT columns, a partial unique index, and dirty typed values."""
    src = tmp_path / "src.db"
    con = sqlite3.connect(src)
    con.executescript("""
    CREATE TABLE users(
      id TEXT PRIMARY KEY, role TEXT NOT NULL DEFAULT 'customer', name TEXT,
      pts INTEGER NOT NULL DEFAULT 0, pref TEXT NOT NULL DEFAULT '{}', created_at INTEGER);
    CREATE TABLE pandits(
      id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), name TEXT NOT NULL,
      pf REAL DEFAULT 1, spec TEXT DEFAULT '[]', status TEXT DEFAULT 'pending');
    CREATE TABLE pujas(
      id TEXT PRIMARY KEY, name TEXT NOT NULL, price INTEGER NOT NULL, hidden INTEGER DEFAULT 0);
    CREATE TABLE bookings(
      id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id),
      puja_id TEXT NOT NULL REFERENCES pujas(id),
      pandit_id TEXT REFERENCES pandits(id), date TEXT NOT NULL, slot TEXT NOT NULL,
      status TEXT NOT NULL, q TEXT NOT NULL, pay TEXT NOT NULL, created INTEGER);
    CREATE UNIQUE INDEX idx_pandit_slot ON bookings(pandit_id, date, slot)
      WHERE pandit_id IS NOT NULL AND status NOT IN ('Cancelled');
    CREATE TABLE puja_media(
      id TEXT PRIMARY KEY, puja_id TEXT NOT NULL, filename TEXT NOT NULL,
      alt_text TEXT DEFAULT '', size INTEGER DEFAULT 0, is_published INTEGER DEFAULT 0);
    CREATE TABLE audit_logs(
      id INTEGER PRIMARY KEY, action TEXT NOT NULL, entity TEXT NOT NULL, created_at INTEGER);
    CREATE TABLE orders(
      id TEXT PRIMARY KEY, user_id TEXT, items TEXT, total INTEGER, date TEXT);
    """)
    con.execute("INSERT INTO users VALUES('u1','customer','Asha',50,'{}',1700000000000)")
    con.execute("INSERT INTO users VALUES('u2','customer','Dev',0,'{}',1700000000001)")
    con.execute("INSERT INTO pandits VALUES('p1','pu1','Pt. Ramesh',1.15,'[]','verified')")
    con.execute("INSERT INTO pujas VALUES('satyanarayan','Satyanarayan Katha',2100,0)")
    con.execute("INSERT INTO bookings VALUES('DP2401','u1','satyanarayan','p1','2026-10-01','10:00 AM','Confirmed','{\"total\":4785}','{\"paid\":true}',1700000000002)")
    con.execute("INSERT INTO bookings VALUES('DP2402','u2','satyanarayan',NULL,'2026-10-02','10:00 AM','New','{\"total\":4100}','{\"paid\":false}',1700000000003)")
    con.execute("INSERT INTO puja_media VALUES('pm1','satyanarayan','seed-x.jpg','Durga puja',290015,1)")
    con.execute("INSERT INTO audit_logs(action,entity,created_at) VALUES('media.delete','puja_media',1700000000004)")
    con.execute("INSERT INTO audit_logs(action,entity,created_at) VALUES('password.change','user',1700000000005)")
    # dirty typed values: '' in an INTEGER column, numeric string in another row
    con.execute("INSERT INTO orders VALUES('OR1','u1','[]','','2026-09-01')")
    con.execute("INSERT INTO orders VALUES('OR2','u2','[]','249','2026-09-02')")
    con.commit()
    con.close()
    return src


# --- unit pieces --------------------------------------------------------------
def test_translate_table_identity_and_defaults(tmp_path):
    """Rowid-alias PKs become identity columns; literal defaults survive;
    sqlite-only default expressions (unixepoch etc.) are dropped."""
    p = tmp_path / "t.db"
    con = sqlite3.connect(p)
    con.execute("CREATE TABLE t(id INTEGER PRIMARY KEY, name TEXT NOT NULL DEFAULT 'x', "
                "at INTEGER DEFAULT (unixepoch() * 1000))")
    con.commit(); con.close()
    plan = mig.introspect(p, only={"t"})
    stmt = mig.translate_table(plan["tables"]["t"])[0]
    assert "GENERATED BY DEFAULT AS IDENTITY" in stmt, "rowid alias -> identity"
    assert "DEFAULT 'x'" in stmt, "safe literal default kept"
    assert "unixepoch" not in stmt, "sqlite-only default expressions dropped"


def test_translate_index_partial_unique_passes_through():
    sqls = mig.translate_indexes([{
        "name": "idx_pandit_slot", "table": "bookings",
        "sql": "CREATE UNIQUE INDEX idx_pandit_slot ON bookings(pandit_id, date, slot) "
               "WHERE pandit_id IS NOT NULL AND status NOT IN ('Cancelled')"}])
    assert sqls and "IF NOT EXISTS" in sqls[0] and "WHERE pandit_id IS NOT NULL" in sqls[0]


def test_coerce_values():
    intcol = mig.Column("total", "INTEGER", False, None, 0)
    txtcol = mig.Column("name", "TEXT", False, None, 0)
    realcol = mig.Column("pf", "REAL", False, None, 0)
    assert mig.coerce_value(intcol, "") is None, "empty string -> NULL for numeric"
    assert mig.coerce_value(intcol, "249") == 249
    assert mig.coerce_value(intcol, 12) == 12
    assert mig.coerce_value(realcol, "1.15") == 1.15
    assert mig.coerce_value(realcol, "") is None
    assert mig.coerce_value(txtcol, 12) == "12"
    assert mig.coerce_value(txtcol, None) is None


# --- end-to-end on the synthetic source ----------------------------------------
@pytest.mark.asyncio
async def test_full_pipeline_synthetic(tmp_path):
    src = _make_source(tmp_path)
    tgt_file = tmp_path / "tgt.db"
    plan = mig.introspect(src)
    order = plan["order"]
    assert order.index("users") < order.index("bookings"), "parents before children"
    result = await mig.run_migration(src, mig.SqliteTarget(str(tgt_file)), truncate=True)
    assert result["ok"], result["report"]
    assert result["copied"]["users"] == 2
    assert result["copied"]["bookings"] == 2
    assert result["copied"]["audit_logs"] == 2
    assert result["created"], "tables were created by the tool"
    # verification details: counts and max(id) match
    assert result["report"]["bookings"]["ok"]
    assert result["report"]["audit_logs"]["max_id"]["source"] == 2
    # dirty values coerced: orders.total '' -> NULL, '249' -> 249
    con = sqlite3.connect(tgt_file)
    rows = con.execute("SELECT id, total FROM orders ORDER BY id").fetchall()
    con.close()
    assert rows[0][1] is None and rows[1][1] == 249
    # partial unique index really exists and is enforced on the target
    con = sqlite3.connect(tgt_file)
    idx = con.execute("SELECT sql FROM sqlite_master WHERE name='idx_pandit_slot'").fetchone()
    con.close()
    assert idx and "UNIQUE" in idx[0]


# --- dress rehearsal against the REAL production database ----------------------
@pytest.mark.skipif(not REAL_DB.exists(), reason="real daivikpooja.db not present")
@pytest.mark.asyncio
async def test_dress_rehearsal_real_database(tmp_path):
    """Copy every table of the production SQLite into a throwaway target and
    verify counts + max ids — the same run the cutover will do with a DSN."""
    tgt_file = tmp_path / "rehearsal.db"
    result = await mig.run_migration(REAL_DB, mig.SqliteTarget(str(tgt_file)), truncate=True)
    assert result["ok"], "verification failed: " + str(result["report"])
    plan = mig.introspect(REAL_DB)
    # every table copied with the exact source count
    for t, n in plan["counts"].items():
        assert result["copied"][t] == n, t
    # key tables preserved with their real ids
    con = sqlite3.connect(tgt_file)
    ids = {
        "users": [r[0] for r in con.execute("SELECT id FROM users")],
        "bookings": [r[0] for r in con.execute("SELECT id FROM bookings")],
        "puja_media": [r[0] for r in con.execute("SELECT id FROM puja_media")],
        "pujas": [r[0] for r in con.execute("SELECT id FROM pujas")],
    }
    booking = con.execute("SELECT id, q, pay FROM bookings LIMIT 1").fetchone()
    media = con.execute("SELECT id, alt_text, is_published FROM puja_media LIMIT 1").fetchone()
    con.close()
    src_con = sqlite3.connect(f"file:{REAL_DB}?mode=ro", uri=True)
    src_users = {r[0] for r in src_con.execute("SELECT id FROM users")}
    src_bookings = {r[0] for r in src_con.execute("SELECT id FROM bookings")}
    src_media = {r[0] for r in src_con.execute("SELECT id FROM puja_media")}
    src_pujas = {r[0] for r in src_con.execute("SELECT id FROM pujas")}
    src_con.close()
    assert set(ids["users"]) == src_users, "user ids preserved"
    assert set(ids["bookings"]) == src_bookings, "booking ids preserved"
    assert set(ids["puja_media"]) == src_media, "photo metadata ids preserved"
    assert set(ids["pujas"]) == src_pujas, "puja ids preserved"
    # JSON columns arrive intact and parseable
    import json
    assert isinstance(json.loads(booking[1]), dict), "booking q JSON intact"
    assert isinstance(json.loads(booking[2]), dict), "booking pay JSON intact"
    assert isinstance(media[1], str), "photo alt_text intact"


@pytest.mark.skipif(not REAL_DB.exists(), reason="real daivikpooja.db not present")
@pytest.mark.asyncio
async def test_dry_run_makes_no_writes(tmp_path):
    tgt_file = tmp_path / "dry.db"
    result = await mig.run_migration(REAL_DB, mig.SqliteTarget(str(tgt_file)), dry_run=True)
    assert result.get("dry_run") is True
    assert result["counts"].get("users", 0) > 0
    assert not tgt_file.exists() or sqlite3.connect(tgt_file).execute(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table'").fetchone()[0] == 0, \
        "dry run created no tables"
